services:
  app:
    build: .
    ports:
      - 8000:8000
    command:
      - mkdocs
      - serve
      - '-a'
      - '0.0.0.0:8000'
    develop:
      watch:
        - action: sync
          path: .
          target: /app
