site_name: Why, Scott, WHY?!?
site_url: https://ddrscott.github.io
repo_name: null
repo_url: null # https://github.com/ddrscott/ddrscott.github.io
# git@github.com:ddrscott/ddrscott.github.io.git
# Copyright
copyright: 'Copyright &copy; 2014 - 2021 Scott Pierce'

theme:
  name: material
  custom_dir: custom
  # logo:
  #   icon: "\uE8AF"
  features:
    # tabs: false
  palette:
    primary: 'blue grey'
    accent: 'orange'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ddrscott
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_ddrscott_
  disqus: ddrscottgithubio

extra_javascript:
  - 'https://platform.twitter.com/widgets.js'

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


google_analytics:
  - 'UA-50126719-1'
  - 'auto'

plugins: ['search', 'macros', 'custom']

nav:
  - Latest Posts: index.md
  - About: about.md
  - Projects: projects.md
  - Vim: 
    - 'Getting Rusty with Vim': blog/2018/getting-rusty-with-vim.markdown
    - 'Vim Send Text': blog/2017/vim-send-text.markdown
    - 'Vim Toggle Movement: I Just Want to Go Home': blog/2016/vim-toggle-movement.markdown
    - 'Yank Without Jank': blog/2016/yank-without-jank.markdown
    - 'Sensible Horizontal Scroll in Vim': blog/2016/sidescroll.markdown
    - 'Vim Side Search: Making Search Fun Again': blog/2016/side-search.markdown
    - 'Making a Window Submode in Vim': blog/2016/making-a-window-submode.markdown
    - 'BS to the Black Hole': blog/2016/bs-to-the-black-hole.markdown
    - 'PSA: Vim Modulo ''%'' Returns Negative Numbers!': blog/2016/negative-modulo.markdown
  - SQL: 
    - 'SQL + Jinja = Templating Done Right™': blog/2020/sql-ninja.markdown
    - 'What the SQL?! Lateral Joins': blog/2017/what-the-sql-lateral.markdown
    - 'What the SQL?! WINDOW': blog/2017/what-the-sql-window.markdown
    - 'What the SQL?! Recursive': blog/2017/what-the-sql-recursive.markdown
    - 'What the SQL?! JOIN me at UNION Station': blog/2018/join-me-at-union-station.markdown
  - '2021': 
    - 'I Heart Make': blog/2021/i-heart-make.markdown
  - '2020': 
    - 'SQL + Jinja = Templating Done Right™': blog/2020/sql-ninja.markdown
  - '2018':
    - 'Move to MkDocs': blog/2018/move-to-mkdocs.markdown
    - 'A Rustic Journey Through Stream Stats': blog/2018/stream-stats-in-rust.markdown
    - 'Getting Rusty with Vim': blog/2018/getting-rusty-with-vim.markdown
    - 'Dev Blog Tools :: A Quick Tour of My Setup': blog/2018/blog-setup.markdown
    - 'What the SQL?! JOIN me at UNION Station': blog/2018/join-me-at-union-station.markdown
  - '2017':
    - 'Base16 Shell': blog/2017/base16-shell.markdown
    - 'How to Get Better At Anything': blog/2017/how-to-get-better-at-anything.markdown
    - 'FZF + WordNet = Dictionary': blog/2017/fzf-dictionary.markdown
    - 'GNU Screen': blog/2017/gnu-screen.markdown
    - 'What the SQL?!? Lateral Joins': blog/2017/what-the-sql-lateral.markdown
    - 'What the SQL?!? WINDOW': blog/2017/what-the-sql-window.markdown
    - 'What the SQL?!? Recursive': blog/2017/what-the-sql-recursive.markdown
    - 'Vim Send Text': blog/2017/vim-send-text.markdown
  - '2016':
    - 'PSA: Vim Modulo ''%'' Returns Negative Numbers!': blog/2016/negative-modulo.markdown
    - 'Photography Refactored': blog/2016/photography-lightening-talk.markdown
    - 'Ruby Abuse: How Not to Write Ruby, But Still Have Fun': blog/2016/ruby-abuse.markdown
    - 'Making a Window Submode in Vim': blog/2016/making-a-window-submode.markdown
    - 'ANSI Codes with Character': blog/2016/ansi-codes-with-character.markdown
    - 'Vim Toggle Movement: I Just Want to Go Home': blog/2016/vim-toggle-movement.markdown
    - 'Yank Without Jank': blog/2016/yank-without-jank.markdown
    - 'Sensible Horizontal Scroll in Vim': blog/2016/sidescroll.markdown
    - 'Vim Side Search: Making Search Fun Again': blog/2016/side-search.markdown
    - 'BS to the Black Hole': blog/2016/bs-to-the-black-hole.markdown
  - '2014':
    - 'Tech Stack 2014 Edition': blog/2014/tech-stack-2014-edition.markdown
    - 'Octopress to the Rescue': blog/2014/octopress-to-the-rescue.markdown
  - About: about.md
# vim:fdm=indent
