name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: source-project

    - name: Clone ddrscott.github.io
      uses: actions/checkout@v2
      with:
        repository: ddrscott/ddrscott.github.io
        path: ddrscott.github.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        cd source-project
        docker build . -t mkdocs

    - name: Build and Deploy
      run: |
        cd source-project
        docker run -t --rm  -v ${PWD}:/app -v ${site_path}:/site mkdocs build --site-dir /site
      env:
        site_path: ${{ github.workspace }}/ddrscott.github.io
