name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: source-project # Optional: Specify a path to clone the source project into

    - name: Clone ddrscott.github.io
      uses: actions/checkout@v2
      with:
        repository: ddrscott/ddrscott.github.io
        path: ddrscott.github.io # Clone into 'ddrscott.github.io' directory
        token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN or your personal token if needed

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Deploy
      run: |
        cd source-project # Navigate into the source project directory if you used a path above
        make deploy
      env:
        site_path: ${{ github.workspace }}/ddrscott.github.io
